<%
out.println("<!DOCTYPE html>");
out.println("<html lang=\"en\">");
out.println("<head>");
out.println("    <meta charset=\"ISO-8859-1\">");
out.println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
out.println("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">");
out.println("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>");
out.println("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&display=swap\" rel=\"stylesheet\">");
out.println("    <link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined\" rel=\"stylesheet\" />");
out.println("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css\">");
out.println("    <link rel=\"stylesheet\" href=\"index.css\">");
out.println("    ");
out.println("     <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">");
out.println("    <title>Pet Store Landing Page</title>");
out.println("    ");

out.println(".sear input[type=text] ");
out.println("  float: right;");
out.println("  padding: 6px;");
out.println("  border: 1px solid black;");
out.println("  margin-top: 8px;");
out.println("  margin-right: 16px;");
out.println("  font-size: 17px;");

out.println("");
out.println("@media screen and (max-width: 600px) {");
out.println(" .sear input[type=text] {");
out.println("    float: none;");
out.println("    display: block;");
out.println("    text-align: left;");
out.println("    width: 100%;");
out.println("    margin: 0;");
out.println("    padding: 14px;");

out.println("  .sear input[type=text] {");
out.println("    border: 1px solid #ccc;");


out.println(" ");
out.println(" </style>");
out.println("    ");
out.println("</head>");
out.println("<body>");
out.println("    <header>");
out.println("      <div class=\"banner\">Get free delivery on orders</div>");
out.println("        <nav>");
out.println("         ");
out.println("            <div id=\"logo\">");
out.println("");
out.println("                <svg width=\"40\" height=\"32\" viewBox=\"0 0 40 32\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">");
out.println("                    <path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M12.8 32H0V21.9849C0 17.1239 4.0116 13.1839 8.96 13.1839H15.2V0.468341C15.2 0.251458 15.3792 0.0754376 15.6 0.0754376C15.7184 0.0754376 15.8308 0.127301 15.9068 0.216883L17.3616 1.92719C18.402 1.07577 19.74 0.563816 21.2 0.563816H22C23.442 0.563816 24.7656 1.06359 25.8 1.89654L27.2932 0.14066C27.3692 0.0514706 27.4812 0 27.6 0C27.8208 0 28 0.175628 28 0.392904V15.3896H23.36C17.528 15.3896 12.8 20.0337 12.8 25.7623V32Z\" fill=\"#45413E\" />");
out.println("                    <path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M29.76 17.0569V12.0875C29.76 12.0836 29.76 12.0797 29.76 12.0758V6.79004C29.76 6.57435 29.9392 6.4 30.16 6.4C30.266 6.4 30.3676 6.44095 30.4424 6.51389L31.9576 7.98784C32.7864 7.42501 33.7936 7.09504 34.88 7.09504C35.97 7.09504 36.9808 7.42735 37.8112 7.99369L39.3176 6.52793C39.3924 6.45499 39.494 6.41404 39.6 6.41404C39.8208 6.41404 40 6.58878 40 6.80408V23.2632C40 28.0883 35.9884 32 31.04 32H14.4V25.7938C14.4 20.969 18.4116 17.0569 23.36 17.0569H29.76Z\" fill=\"#45413E\" />");
out.println("                </svg>");
out.println("                Basu <br> Pet Store");
out.println("            </div>");
out.println("            <ul class=\"navigation-menu\">");
out.println("            ");
out.println("             <li><a href=\"loginandregister.html\">Home</a>");
out.println("                </li>");
out.println("            ");
out.println("                <li><a href=\"product.html\">Products</a>");
out.println("                    <!-- <ul class=\"subnav\">");
out.println("                        <li class=\"card-med\" id=\"sup-dog\">");
out.println("                            <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/qPvaAv2gxwM3l0z7dl_eoh9v6h58HlzewBUfEgX6AZE/rs:fit:368:386/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvMTIv/ZmM4YjNlYmItMDNj/Ni00NGM3LTliNGUt/YTUyOWUzOGU4NTE2/LnBuZw.png\"></div>");
out.println("                            <a href=\"#\">");
out.println("                                <span>Dogs</span>");
out.println("                                <span>Shop All <span class=\"material-symbols-outlined\">");
out.println("                                        arrow_forward");
out.println("                                    </span></span>");
out.println("                            </a>");
out.println("                        </li>");
out.println("                        <li class=\"card-med\" id=\"sup-cat\">");
out.println("                            <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/US6gJ6fHUOJqruLB7KDe5zEa82iDSp7OdO-bv-aLtvU/rs:fit:368:310/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvNjU5/LzdmOWU1ZjU0LTMx/ZDQtNDgwNS1iM2E2/LWM3NzgyMTcyNzJh/NC5wbmc.png\"></div>");
out.println("                            <a href=\"#\">");
out.println("                                <span>Cats</span>");
out.println("                                <span>Shop All <span class=\"material-symbols-outlined\">");
out.println("                                        arrow_forward");
out.println("                                    </span></span>");
out.println("                            </a>");
out.println("                        </li>");
out.println("                        <li class=\"card-med\" id=\"sup-bird\">");
out.println("                            <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/6OkSfKKP476ZKzGJoDlXfXuWzX-vjlDRotIVMTz3lmo/rs:fit:368:396/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvNzA1/LzRkNmI1YjIwLTQy/YWQtNDVlMC05ZDI5/LTA0MTkyMWZkNWE1/NS5wbmc.png\"></div>");
out.println("                            <a href=\"#\">");
out.println("                                <span>Birds</span>");
out.println("                                <span>Shop All <span class=\"material-symbols-outlined\">");
out.println("                                        arrow_forward");
out.println("                                    </span></span>");
out.println("                            </a>");
out.println("                        </li>");
out.println("                        <li class=\"card-med\" id=\"sup-fish\">");
out.println("                            <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/41Pv7w9rcbn7II_gB2vwvVCQRYE5mvpca1ZbsvMujR0/rs:fit:368:368/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvNjE5/LzRlZjE1YTgyLTI3/NjYtNDlkNC1hMGE3/LWY4ZjRmNzhjM2M5/NS5wbmc.png\"></div>");
out.println("                            <a href=\"#\">");
out.println("                                <span>Fish</span>");
out.println("                                <span>Shop All <span class=\"material-symbols-outlined\">");
out.println("                                        arrow_forward");
out.println("                                    </span></span>");
out.println("                            </a>");
out.println("                        </li>");
out.println("                    </ul> -->");
out.println("                <li><a href=\"service.html\">Services</a>");
out.println("                    <!-- <ul class=\"subnav\">");
out.println("                        <li class=\"card-med\" id=\"serv-groom\">");
out.println("                            <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/T11rfGmMKgcStJyAFKNgtOfE79cadabx0DVMnvzA9Pk/rs:fit:368:313/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvNDQx/LzFlYWU4MWY3LWQ1/ZjYtNDM2Ny1hZjM5/LWVmNTFmMGM5Njk4/MS5wbmc.png\"></div>");
out.println("                            <a href=\"#\">");
out.println("                                <span>Grooming</span>");
out.println("                                <span>More Info <span class=\"material-symbols-outlined\">");
out.println("                                        arrow_forward");
out.println("                                    </span></span>");
out.println("                            </a>");
out.println("                        </li>");
out.println("                        <li class=\"card-med\" id=\"serv-board\">");
out.println("                            <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/F5Ea1suZtMYimKDkJr0CJLO_1bju6-bTyT1EuDKEg8s/rs:fit:368:254/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvMjcx/LzVjMzE4NWM0LWZh/NTMtNGQ1OS05ZTM2/LTZjYzBhNGU3ODg0/NC5wbmc.png\"></div>");
out.println("                            <a href=\"#\">");
out.println("                                <span>Boarding</span>");
out.println("                                <span>More Info<span class=\"material-symbols-outlined\">");
out.println("                                        arrow_forward");
out.println("                                    </span></span>");
out.println("                            </a>");
out.println("                    </ul>");
out.println("                </li> -->");
out.println("                <li><a href=\"location.html\">Locations & Hours</a>");
out.println("                </li>");
out.println("                <li>");
out.println("                    <a href=\"aboutus.html\">About Us</a>");
out.println("                </li>");
out.println("            </ul>");
out.println("            <div id=\"utility\">");
out.println("               <!-- <span class=\"material-symbols-outlined\">");
out.println("                    search");
out.println("                </span> -->");
out.println("                <input type=\"text\"  class=\"sear\"  placeholder=\"Search..\">");
out.println("       ");
out.println("                <span class=\"material-symbols-outlined\">");
out.println("                    shopping_cart");
out.println("                </span>");
out.println("            </div>");
out.println("        </nav>");
out.println("    </header>");
out.println("    <section>");
out.println("        <h2>Shop by Pet</h2>");
out.println("");
out.println("        <ul class=\"shop-pets\">");
out.println("            <li class=\"card-large card-light\" id=\"sup-dog\">");
out.println("                <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/5ccPOQq69UKQcbmXfjvOScfFc9NXKG0Xu6DPNQ8b0f8/rs:fit:368:247/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvMTEw/LzFlODdiYzcyLTBl/OWEtNDFlNS05N2Ey/LTMzYTA4MDQ5MWU1/OC5wbmc.png\"></div>");
out.println("                <ul>");
out.println("                    Dogs");
out.println("                    <li><a href=\"#\">Food & Treats</a></li>");
out.println("                    <li><a href=\"#\">Toys</a></li>");
out.println("                    <li><a href=\"#\">Beds & Furniture</a></li>");
out.println("                    <li><a href=\"#\">Outdoor Supplies</a></li>");
out.println("                    <li><a href=\"#\">Clothing</a></li>");
out.println("");
out.println("                    <button class=\"btn-outline-light\">Shop All<span class=\"material-symbols-outlined\">");
out.println("                            arrow_forward");
out.println("                        </span></button>");
out.println("                </ul>");
out.println("            </li>");
out.println("");
out.println("            <li class=\"card-large card-dark\" id=\"sup-cat\">");
out.println("                <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/RjiKOF2gGKiIVnIMFi0O1a4aU7DoHfhbkXr2JbUYZ3A/rs:fit:368:313/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvMzEy/LzliNDQ3MmVlLWZh/YjMtNDQwNy1iOWVh/LWMwOTdlYWNjNWE3/NS5wbmc.png\"></div>");
out.println("                <ul>Cats");
out.println("                    <li><a href=\"#\">Food & Treats</a></li>");
out.println("                    <li><a href=\"#\">Toys</a></li>");
out.println("                    <li><a href=\"#\">Beds & Furniture</a></li>");
out.println("                    <button class=\"btn-outline-dark\">Shop All<span class=\"material-symbols-outlined\">");
out.println("                            arrow_forward");
out.println("                        </span></button>");
out.println("                </ul>");
out.println("");
out.println("            </li>");
out.println("");
out.println("            <li class=\"card-large card-dark\" id=\"sup-bird\">");
out.println("                <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/DF-XRInvbvWS9fQSpWc_SegC3meXZK8BmE-PjrdrF3Q/rs:fit:368:396/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvNzI3/LzQyYWIyNzliLWJj/ZDgtNGEyMC04MGRi/LTk3MzU4YWFmNTVk/OS5wbmc.png\"> </div>");
out.println("                <ul>Birds");
out.println("                    <li><a href=\"#\">Food & Treats</a></li>");
out.println("                    <li><a href=\"#\">Toys</a></li>");
out.println("                    <li><a href=\"#\">Furniture</a></li>");
out.println("                    <button class=\"btn-outline-dark\">Shop All<span class=\"material-symbols-outlined\">");
out.println("                            arrow_forward");
out.println("                        </span></button>");
out.println("                </ul>");
out.println("");
out.println("            </li>");
out.println("            <li class=\"card-large card-light\" id=\"sup-fish\">");
out.println("                <div class=\"card-image\"><img src=\"https://ouch-cdn2.icons8.com/41Pv7w9rcbn7II_gB2vwvVCQRYE5mvpca1ZbsvMujR0/rs:fit:368:368/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvNjE5/LzRlZjE1YTgyLTI3/NjYtNDlkNC1hMGE3/LWY4ZjRmNzhjM2M5/NS5wbmc.png\"></div>");
out.println("                <ul>");
out.println("                    Fish");
out.println("                    <li><a href=\"#\">Food</a></li>");
out.println("                    <li><a href=\"#\">Aquariums</a></li>");
out.println("                    <li><a href=\"#\">Rocks & Decorations</a></li>");
out.println("                    <button class=\"btn-outline-light\">Shop All<span class=\"material-symbols-outlined\">");
out.println("                            arrow_forward");
out.println("                        </span></button>");
out.println("                </ul>");
out.println("");
out.println("            </li>");
out.println("        </ul>");
out.println("    </section>");
out.println("    </body>");
out.println("    </html>");
%>